export const LeaderBoardDummydata = [
  { name: "Ayesha Rahman", points: 980, location: "Dhaka" },
  { name: "Tanvir Hossain", points: 950, location: "Chittagong" },
  { name: "Nadia Karim", points: 920, location: "Khulna" },
  { name: "Imran Chowdhury", points: 910, location: "Rajshahi" },
  { name: "Farhana Jahan", points: 900, location: "Sylhet" },
  { name: "Zubair Ahmed", points: 890, location: "Barisal" },
  { name: "Maliha Islam", points: 875, location: "Dhaka" },
  { name: "Rafiq Mia", points: 860, location: "Chittagong" },
  { name: "Sadia Nowshin", points: 855, location: "Rangpur" },
  { name: "Tariq Aziz", points: 845, location: "Comilla" },
  { name: "Anika Tasnim", points: 840, location: "Mymensingh" },
  { name: "Rezaul Karim", points: 830, location: "Sylhet" },
  { name: "Mahinur Akter", points: 820, location: "Jessore" },
  { name: "Nasir Uddin", points: 810, location: "Dhaka" },
  { name: "Tahmina Haque", points: 800, location: "Chittagong" },
  { name: "Khalid Hasan", points: 790, location: "Khulna" },
  { name: "Lamia Akhter", points: 780, location: "Dhaka" },
  { name: "Hossain Ali", points: 770, location: "Rajshahi" },
  { name: "Jannat Zerin", points: 760, location: "Barisal" },
  { name: "Salman Khan", points: 750, location: "Sylhet" },
  { name: "Tania Ferdous", points: 740, location: "Gazipur" },
  { name: "Asif Mahmud", points: 730, location: "Narayanganj" },
];